### ISSUE TITLE
Clicking on "My Profile" gives back errors

### ISSUE THREAD

**Issue by voidpublic** [Thangiee/LoL-Hangouts#1]
Seems like it doesn't recognize my ingame name when logging in:
http://imgur.com/HV34WhL,cWDh4S2

Did i miss a setting?

**Comment by voidpublic** [comment]
Region EUW in case you wondered

**Comment by Thangiee** [comment]
Can you tell me your username?

Also could you try logging out and then back in again and if that doesn't
work, try killing the app and login again.

I'll try to dig into this issue and get it fix ASAP. Sorry for the
inconvenience.

**Comment by voidpublic** [comment]
Logging in works fine. 

BR0C0NUT is my IGN. 

Killing / relogging doesnt fix it :)

**Comment by Thangiee** [comment]
Can you answer the following questions to help me narrow the problem:

-Has it work before or did problem just appear?

-When you are having this problem, dose the friends list still show your
friends or is it blank?

-Is your in game username different than your username you used to login?

**Comment by voidpublic** [comment]
never worked before.

I can still use my chatlist, and chat with friends.

ingame name is different to my username.

**Comment by Thangiee** [comment]
I just uploaded the new version to the play store that attempts to fix your problem. And by attempt, I mean that I haven't test if it works or not since I don't have an account with with different login/username (i think this is what causing the issues). 

So when have the time, please verify and tell me if it works or not. Thanks!

**Comment by voidpublic** [comment]
many people have a different ign and a loginname, especially those that are changing their ingame name, don't see the update yet in the store

**Comment by Thangiee** [comment]
Update just went live in the play store. :)

**Comment by voidpublic** [comment]
-> works many thanks
